package com.mycompany.thymeleafspringapp.model;
// Generated Jan 22, 2015 10:22:48 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deals generated by hbm2java
 */
public class Deals  implements java.io.Serializable {


     private long dealId;
     private Instruments instruments;
     private Users users;
     private boolean longDeal;
     private double priceOpen;
     private Double priceClose;
     private Date dateOpen;
     private Date dateClose;
     private String description;
     private Set screenshotses = new HashSet(0);
     private Set tagses = new HashSet(0);

    public Deals() {
    }

	
    public Deals(long dealId, Instruments instruments, Users users, boolean longDeal, double priceOpen) {
        this.dealId = dealId;
        this.instruments = instruments;
        this.users = users;
        this.longDeal = longDeal;
        this.priceOpen = priceOpen;
    }
    public Deals(long dealId, Instruments instruments, Users users, boolean longDeal, double priceOpen, Double priceClose, Date dateOpen, Date dateClose, String description, Set screenshotses, Set tagses) {
       this.dealId = dealId;
       this.instruments = instruments;
       this.users = users;
       this.longDeal = longDeal;
       this.priceOpen = priceOpen;
       this.priceClose = priceClose;
       this.dateOpen = dateOpen;
       this.dateClose = dateClose;
       this.description = description;
       this.screenshotses = screenshotses;
       this.tagses = tagses;
       
    }
   
    public long getDealId() {
        return this.dealId;
    }
    
    public void setDealId(long dealId) {
        this.dealId = dealId;
    }
    public Instruments getInstruments() {
        return this.instruments;
    }
    
    public void setInstruments(Instruments instruments) {
        this.instruments = instruments;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public boolean isLongDeal() {
        return this.longDeal;
    }
    
    public void setLongDeal(boolean longDeal) {
        this.longDeal = longDeal;
    }
    public double getPriceOpen() {
        return this.priceOpen;
    }
    
    public void setPriceOpen(double priceOpen) {
        this.priceOpen = priceOpen;
    }
    public Double getPriceClose() {
        return this.priceClose;
    }
    
    public void setPriceClose(Double priceClose) {
        this.priceClose = priceClose;
    }
    public Date getDateOpen() {
        return this.dateOpen;
    }
    
    public void setDateOpen(Date dateOpen) {
        this.dateOpen = dateOpen;
    }
    public Date getDateClose() {
        return this.dateClose;
    }
    
    public void setDateClose(Date dateClose) {
        this.dateClose = dateClose;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getScreenshotses() {
        return this.screenshotses;
    }
    
    public void setScreenshotses(Set screenshotses) {
        this.screenshotses = screenshotses;
    }
    public Set getTagses() {
        return this.tagses;
    }
    
    public Set getTagsNames() {
        Set<String> result= new HashSet<>(); 
        for(Object t:this.tagses){
            Tags tag=(Tags)t;
            result.add(tag.getTag());
        }
        return result;
    }
    
    
    public void setTagses(Set tagses) {
        this.tagses = tagses;
    }




}


