package com.mycompany.thymeleafspringapp.model;
// Generated Jan 22, 2015 10:22:48 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Instruments generated by hbm2java
 */
public class Instruments  implements java.io.Serializable {


     private long instrumentId;
     private String instrumentName;
     private String instrumentCode;
     private Set dealses = new HashSet(0);

    public Instruments() {
    }

	
    public Instruments(long instrumentId) {
        this.instrumentId = instrumentId;
    }
    public Instruments(long instrumentId, String instrumentName, String instrumentCode, Set dealses) {
       this.instrumentId = instrumentId;
       this.instrumentName = instrumentName;
       this.instrumentCode = instrumentCode;
       this.dealses = dealses;
    }
   
    public long getInstrumentId() {
        return this.instrumentId;
    }
    
    public void setInstrumentId(long instrumentId) {
        this.instrumentId = instrumentId;
    }
    public String getInstrumentName() {
        return this.instrumentName;
    }
    
    public void setInstrumentName(String instrumentName) {
        this.instrumentName = instrumentName;
    }
    public String getInstrumentCode() {
        return this.instrumentCode;
    }
    
    public void setInstrumentCode(String instrumentCode) {
        this.instrumentCode = instrumentCode;
    }
    public Set getDealses() {
        return this.dealses;
    }
    
    public void setDealses(Set dealses) {
        this.dealses = dealses;
    }




}


