package com.mycompany.thymeleafspringapp.model;
// Generated Jan 22, 2015 10:22:48 PM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {


     private long tagId;
     private Deals deals;
     private String tag;

    public Tags() {
    }

    public Tags(long tagId, Deals deals, String tag) {
       this.tagId = tagId;
       this.deals = deals;
       this.tag = tag;
    }
   
    public long getTagId() {
        return this.tagId;
    }
    
    public void setTagId(long tagId) {
        this.tagId = tagId;
    }
    public Deals getDeals() {
        return this.deals;
    }
    
    public void setDeals(Deals deals) {
        this.deals = deals;
    }
    public Serializable getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }




}


