package com.mycompany.thymeleafspringapp.model;
// Generated Jan 10, 2015 9:31:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserGroups generated by hbm2java
 */
@Entity
@Table(name="user_groups"
    ,schema="trdr"
)
public class UserGroups  implements java.io.Serializable {


     private long userGroupId;
     private String userGroupNme;
     private String groupPurpose;
     private Set userRolesPts = new HashSet(0);
     private Set userGroupsPts = new HashSet(0);

    public UserGroups() {
    }

	
    public UserGroups(long userGroupId) {
        this.userGroupId = userGroupId;
    }
    public UserGroups(long userGroupId, String userGroupNme, String groupPurpose, Set userRolesPts, Set userGroupsPts) {
       this.userGroupId = userGroupId;
       this.userGroupNme = userGroupNme;
       this.groupPurpose = groupPurpose;
       this.userRolesPts = userRolesPts;
       this.userGroupsPts = userGroupsPts;
    }
   
     @Id 

    
    @Column(name="user_group_id", unique=true, nullable=false)
    public long getUserGroupId() {
        return this.userGroupId;
    }
    
    public void setUserGroupId(long userGroupId) {
        this.userGroupId = userGroupId;
    }

    
    @Column(name="user_group_nme", length=50)
    public String getUserGroupNme() {
        return this.userGroupNme;
    }
    
    public void setUserGroupNme(String userGroupNme) {
        this.userGroupNme = userGroupNme;
    }

    
    @Column(name="group_purpose", length=100)
    public String getGroupPurpose() {
        return this.groupPurpose;
    }
    
    public void setGroupPurpose(String groupPurpose) {
        this.groupPurpose = groupPurpose;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userGroups")
    public Set getUserRolesPts() {
        return this.userRolesPts;
    }
    
    public void setUserRolesPts(Set userRolesPts) {
        this.userRolesPts = userRolesPts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userGroups")
    public Set getUserGroupsPts() {
        return this.userGroupsPts;
    }
    
    public void setUserGroupsPts(Set userGroupsPts) {
        this.userGroupsPts = userGroupsPts;
    }




}


