package com.mycompany.thymeleafspringapp.model;
// Generated Jan 10, 2015 9:31:57 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "trdr", uniqueConstraints = {
    @UniqueConstraint(columnNames = "username"),
    @UniqueConstraint(columnNames = "email")}
)
public class Users implements java.io.Serializable {

    private long userId;
    private String username;
    private String password;
    private String email;
    private Boolean enabled;
    private Set userGroupsPts = new HashSet(0);
    private Set userRolesPts = new HashSet(0);

    public Users() {
    }

    public Users(long userId, String username, String password, String email) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
    }

    public Users(long userId, String username, String password, String email, Boolean enabled, Set userGroupsPts, Set userRolesPts) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.enabled = enabled;
        this.userGroupsPts = userGroupsPts;
        this.userRolesPts = userRolesPts;
    }

    public Users(long userId, String username, String password, String email, Boolean enabled) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.enabled = enabled;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "user_id", unique = true, nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "username", unique = true, nullable = false, length = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "email", unique = true, nullable = false, length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "enabled")
    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set getUserGroupsPts() {
        return this.userGroupsPts;
    }

    public void setUserGroupsPts(Set userGroupsPts) {
        this.userGroupsPts = userGroupsPts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set getUserRolesPts() {
        return this.userRolesPts;
    }

    public void setUserRolesPts(Set userRolesPts) {
        this.userRolesPts = userRolesPts;
    }

}
