package com.mycompany.thymeleafspringapp.model;
// Generated Jan 10, 2015 9:31:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserGroupsPt generated by hbm2java
 */
@Entity
@Table(name="user_groups_pt"
    ,schema="trdr"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "user_group_id", "start_dte"}) 
)
public class UserGroupsPt  implements java.io.Serializable {


     private long userGroupsPtId;
     private Users users;
     private UserGroups userGroups;
     private Date startDte;
     private Date endDte;

    public UserGroupsPt() {
    }

	
    public UserGroupsPt(long userGroupsPtId) {
        this.userGroupsPtId = userGroupsPtId;
    }
    public UserGroupsPt(long userGroupsPtId, Users users, UserGroups userGroups, Date startDte, Date endDte) {
       this.userGroupsPtId = userGroupsPtId;
       this.users = users;
       this.userGroups = userGroups;
       this.startDte = startDte;
       this.endDte = endDte;
    }
   
     @Id 

    
    @Column(name="user_groups_pt_id", unique=true, nullable=false)
    public long getUserGroupsPtId() {
        return this.userGroupsPtId;
    }
    
    public void setUserGroupsPtId(long userGroupsPtId) {
        this.userGroupsPtId = userGroupsPtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_group_id")
    public UserGroups getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(UserGroups userGroups) {
        this.userGroups = userGroups;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_dte", length=13)
    public Date getStartDte() {
        return this.startDte;
    }
    
    public void setStartDte(Date startDte) {
        this.startDte = startDte;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_dte", length=13)
    public Date getEndDte() {
        return this.endDte;
    }
    
    public void setEndDte(Date endDte) {
        this.endDte = endDte;
    }




}


