package com.mycompany.thymeleafspringapp.model;
// Generated Jan 10, 2015 9:31:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name="user_roles"
    ,schema="trdr"
)
public class UserRoles  implements java.io.Serializable {


     private long userRoleId;
     private String roleNme;
     private Set userRolesPts = new HashSet(0);

    public UserRoles() {
    }

	
    public UserRoles(long userRoleId) {
        this.userRoleId = userRoleId;
    }
    public UserRoles(long userRoleId, String roleNme, Set userRolesPts) {
       this.userRoleId = userRoleId;
       this.roleNme = roleNme;
       this.userRolesPts = userRolesPts;
    }
   
     @Id 

    
    @Column(name="user_role_id", unique=true, nullable=false)
    public long getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(long userRoleId) {
        this.userRoleId = userRoleId;
    }

    
    @Column(name="role_nme", length=20)
    public String getRoleNme() {
        return this.roleNme;
    }
    
    public void setRoleNme(String roleNme) {
        this.roleNme = roleNme;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRoles")
    public Set getUserRolesPts() {
        return this.userRolesPts;
    }
    
    public void setUserRolesPts(Set userRolesPts) {
        this.userRolesPts = userRolesPts;
    }




}


