package com.mycompany.thymeleafspringapp.model;
// Generated Jan 10, 2015 9:31:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserRolesPt generated by hbm2java
 */
@Entity
@Table(name="user_roles_pt"
    ,schema="trdr"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_role_id", "start_dte", "user_id", "user_group_id"}) 
)
public class UserRolesPt  implements java.io.Serializable {


     private long userRolesPtId;
     private Users users;
     private UserRoles userRoles;
     private UserGroups userGroups;
     private Date startDte;
     private Date endDte;

    public UserRolesPt() {
    }

	
    public UserRolesPt(long userRolesPtId, Users users, UserRoles userRoles, UserGroups userGroups, Date startDte) {
        this.userRolesPtId = userRolesPtId;
        this.users = users;
        this.userRoles = userRoles;
        this.userGroups = userGroups;
        this.startDte = startDte;
    }
    public UserRolesPt(long userRolesPtId, Users users, UserRoles userRoles, UserGroups userGroups, Date startDte, Date endDte) {
       this.userRolesPtId = userRolesPtId;
       this.users = users;
       this.userRoles = userRoles;
       this.userGroups = userGroups;
       this.startDte = startDte;
       this.endDte = endDte;
    }
   
     @Id 

    
    @Column(name="user_roles_pt_id", unique=true, nullable=false)
    public long getUserRolesPtId() {
        return this.userRolesPtId;
    }
    
    public void setUserRolesPtId(long userRolesPtId) {
        this.userRolesPtId = userRolesPtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role_id", nullable=false)
    public UserRoles getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(UserRoles userRoles) {
        this.userRoles = userRoles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_group_id", nullable=false)
    public UserGroups getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(UserGroups userGroups) {
        this.userGroups = userGroups;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_dte", nullable=false, length=13)
    public Date getStartDte() {
        return this.startDte;
    }
    
    public void setStartDte(Date startDte) {
        this.startDte = startDte;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_dte", length=13)
    public Date getEndDte() {
        return this.endDte;
    }
    
    public void setEndDte(Date endDte) {
        this.endDte = endDte;
    }




}


