package com.mycompany.thymeleafspringapp.model;
// Generated Jan 22, 2015 10:22:48 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long userId;
     private String username;
     private String password;
     private String email;
     private Boolean enabled;
     private Set dealses = new HashSet(0);

    public Users() {
    }

	
    public Users(long userId, String username, String password, String email) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
    }
    
    public Users(long userId, String username, String password, String email, Boolean enabled) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.email = email;
       this.enabled = enabled;
    }
    
    public Users(long userId, String username, String password, String email, Boolean enabled, Set deals) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.email = email;
       this.enabled = enabled;
       this.dealses=deals;
    }
    
    public Users(long userId, String username, String email, Boolean enabled) {
       this.userId = userId;
       this.username = username;
       this.email = email;
       this.enabled = enabled;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    public Set getDealses() {
        return this.dealses;
    }
    
    public void setDealses(Set dealses) {
        this.dealses = dealses;
    }




}


